### ISSUE TITLE
Choosing_actions_highway.pl

### ISSUE THREAD

**Issue by may210297** [CAV-Research-Lab/Safe-Reinforcement-Learning-using-Symbolic-Logical-Programming-for-Autonomous-Highway-Driving#1]
hello, i found the choosing_actions_highway.pl does not exist. Forward to your replay

**Comment by iman-sharifi-ghb** [comment]
Hi, 
Thank you for reaching out. It seems that some of the files haven't been updated using Git. Now, you can see the newest version of the files in the DQNSL folder. You won't have the same problem anymore.

Iman

**Comment by may210297** [comment]
I would try again. Thank you for your contribution!
